plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
WhenitcomestothetopGooglesearchtrendstherearealwaysafewthatstandoutabovetherestForthepastfewweeksthetopspothasbeenheldbyKevinMcCarthySowhoisKevinMcCarthyandwhyishetrendingp.md
droppingoutofSpeakerracep.md
random-1672787972-8197
