plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
paginate: 5  
relative_links:
  enabled: true
  collections: true
  
include:
  -readme.md
  -WhenitcomestothetopGooglesearchtrendstherearealwaysafewthatstandoutabovetherestForthepastfewweeksthetopspothasbeenheldbyKevinMcCarthySowhoisKevinMcCarthyandwhyishetrendingp.md
  -droppingoutofSpeakerracep.md
  -random-1672787972-8197.md 
  -random-1672788186-1122.md
  -random-1672788256-8722.md
  -random-1672788601-13882.md
  -random-1672794240-17359.md
