plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
paginate: 5  
theme: minima
relative_links:
  enabled: true
  collections: true
  
include:
  -/_pages

