name: Generate Article

on:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install openai
          python -m pip install markdown
          python -m pip install pytrends

      - name: Generate article
        run: |
            python main.py ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --local user.email "yzimmermann@ethz.ch"
          git config --local user.name "yzimmermann"
          git pull origin main
          git add article.md
          RANDOM_NAME=random-$(date +%s)-$RANDOM
          git mv article.md $RANDOM_NAME.md
          git mv $RANDOM_NAME.md _posts/$RANDOM_NAME.md
          git commit -m "Generate new article with trending topic"
          git push origin main
