name: Generate Article

on:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install openai
          python -m pip install markdown
          python -m pip install tweepy
      - name: Generate article
        run: |
            python main.py ${{ secrets.TWITTER_CONSUMER_KEY }} ${{ secrets.TWITTER_CONSUMER_SECRET }} ${{ secrets.TWITTER_ACCESS_TOKEN }} ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} ${{ secrets.OPENAI_API_KEY }}
      - name: Set file name
        id: filename
        run: |
          TREND=$(head -n 1 article.md | cut -c 3- | tr -dc '[:alnum:]-')
          echo "::set-output name=filename::${TREND}.md"
      - name: Commit and push changes
        run: |
          git config --local user.email "your@email.com"
          git config --local user.name "Your Name"
          git mv article.md "${{ steps.filename.outputs.filename }}"
          git add "${{ steps.filename.outputs.filename }}"
          git commit -m "Generate new article"
          git push origin main
